### ISSUE TITLE
[BUG] Data not appearing in clipboard when submitting

### ISSUE THREAD

**Issue by EliteMasterEric** [EliteMasterEric/Teyvat.moe#101]
**Describe the bug**
Multiple users (#83 and #97) have been unable to submit data as the data is not being inserted through the clipboard.

**To Reproduce**
The procedure to reproduce this is 

**Expected behavior**
When the user clicks Submit in the Submit Editor Data dialog, the user's clipboard should be filled with the data, but it is not.

**To any users experiencing this bug, please do the following:**

1. Open the browser console (F12 on Firefox and Chrome) and see if any errors appear when you click submit. If so, copy them and paste them here.

2. As a workaround, use the Export Data option in the options menu to export all your preferences, as this also includes the current Editor data.

**Comment by specklet** [comment]
Google Chrome:

Attached is screenshot of error codes that occurred when I opened the map, switched to editor mode, then clicked Submit Data.

Specifically "Uncaught (in promise) DOMException: Document is not focused."

![F12](https://user-images.githubusercontent.com/75462557/101228326-28c78e00-36d6-11eb-9793-40fd52ab1be5.png)

**Comment by EliteMasterEric** [comment]
This issue has hopefully been resolved in v0.8.3.

**Comment by EliteMasterEric** [comment]
Appears to be fixed now.
