### ISSUE TITLE
[EDITOR] Common Chest

### ISSUE THREAD

**Issue by crisrufo** [EliteMasterEric/Teyvat.moe#103]
The following data was generated by this user using the Editor mode. Any required images should be uploaded to this issue by dragging and dropping.
```
PASTE HERE.
![image](https://user-images.githubusercontent.com/75504747/101216908-1bbb8800-365f-11eb-892d-cf4cd1912516.png)

```

**Comment by EliteMasterEric** [comment]
Added in v0.8.4.
