### ISSUE TITLE
[MAPPING] Another map location that I use a lot.

### ISSUE THREAD

**Issue by sgtoutlaw** [EliteMasterEric/Teyvat.moe#104]
Alright I don't know exactly how the title works so hope I did it alright.

There is another location of a chinese interactive map at 

https://wiki.biligame.com/ys/%E5%8E%9F%E7%A5%9E%E5%9C%B0%E5%9B%BE%E5%B7%A5%E5%85%B7_%E5%85%A8%E5%9C%B0%E6%A0%87%E4%BD%8D%E7%BD%AE%E7%82%B9

which has more then the usual locations.  One of the more complete maps that I have to refer to for items other maps don't think is worth considering such as sunsiettas and such for jam.

**Comment by EliteMasterEric** [comment]
Thanks! Added to [this page](https://github.com/GenshinMap/genshinmap.github.io/wiki/Mapping-Resources).
