### ISSUE TITLE
[EDITOR] Exquisite Chest

### ISSUE THREAD

**Issue by CinnamonBread** [EliteMasterEric/Teyvat.moe#105]
The following data was generated by this user using the Editor mode. Any required images should be uploaded to this issue by dragging and dropping.
```
PASTE HERE.
```

**Comment by EliteMasterEric** [comment]
Sorry, without editor data this contribution cannot be accepted.

Please read our full guide here:

https://github.com/GenshinMap/genshinmap.github.io/wiki/Contributing#how-to-contribute-routes-or-markers-contribution
