### ISSUE TITLE
[EDITOR] Common Chest

### ISSUE THREAD

**Issue by Milkys17** [EliteMasterEric/Teyvat.moe#106]
The following data was generated by this user using the Editor mode. Any required images should be uploaded to this issue by dragging and dropping.
```
PASTE HERE.
```
![image](https://user-images.githubusercontent.com/75519340/101236597-0b5de880-3705-11eb-85dc-9900459db0ca.png)

**Comment by EliteMasterEric** [comment]
Sorry, without editor data this contribution cannot be accepted.

Please read our full guide here:

https://github.com/GenshinMap/genshinmap.github.io/wiki/Contributing#how-to-contribute-routes-or-markers-contribution
