### ISSUE TITLE
[BUG] Can't back out when using editor.

### ISSUE THREAD

**Issue by sgtoutlaw** [EliteMasterEric/Teyvat.moe#110]
**Is your feature request related to a problem? Please describe.**
When you are in the editor function, the menus on the right become three editor tabs, but there is no way to go back without scrapping what you are working on as far as I can see.

**Describe the solution you'd like**
Some sort of ability to go back to element standard mode tabs while not scrapping the data you have gathered in editor mode.

**Comment by EliteMasterEric** [comment]
When you disable Editor mode, your work is not scrapped or deleted. If you re-enable editor mode, you can see the elements you were working on again.

Please try it for yourself and let me know if it works that way for you. If it doesn't, that's a bug, and I'd appreciate if you could provide information about your system (what OS and what browser?).

**Comment by sgtoutlaw** [comment]
This is my fault, it seemed that clearing my data allowed me to go back to elements mode, and for some reason I thought it would remove my stuff when I turned editor mode off.  Remove this please.
