### ISSUE TITLE
[EDITOR] common chest

### ISSUE THREAD

**Issue by kishiro0** [EliteMasterEric/Teyvat.moe#113]
Hidden behind a rock
![chest](https://user-images.githubusercontent.com/75644807/101411209-a3b8c080-38f1-11eb-821d-cbc87c062e93.png)
![map](https://user-images.githubusercontent.com/75644807/101411661-6dc80c00-38f2-11eb-940d-ad448f642be2.png)

**Comment by EliteMasterEric** [comment]
Added for v0.8.4.
