### ISSUE TITLE
[BUG] Style breaks in Maxthon 5 browser

### ISSUE THREAD

**Issue by EliteMasterEric** [EliteMasterEric/Teyvat.moe#116]
The only problem is when I open Features->Nature scrollable list overlaps those categories of features.
![Desktop Screenshot 2020 12 09 - 06 37 43 40](https://user-images.githubusercontent.com/62873560/101573084-5fa8e700-39e9-11eb-82ce-b68833a82b5e.png)

_Originally posted by @Shassk in https://github.com/GenshinMap/genshinmap.github.io/issues/108#issuecomment-741506156_

**Comment by EliteMasterEric** [comment]
Closing as the app layout management has been fully reworked and this has likely been resolved.

**Comment by Shassk** [comment]
You mean in beta version? No, it din't help. Actually it became worse - list not only overlaps categories on top (this remained), now it also goes down all the way:

![Desktop Screenshot 2020 12 24 - 11 11 28 29](https://user-images.githubusercontent.com/62873560/103073530-d8f32d00-45d8-11eb-9677-6682a43e4a3e.png)

**Comment by Shassk** [comment]
And it is not scrollable now unlike current release version.
Console: 
`client.js:50 X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.`

**Comment by EliteMasterEric** [comment]
Reopening, I'll look into fixing the problem.

Thanks for testing on the Beta version.

**Comment by EliteMasterEric** [comment]
Since this update the site has undergone a couple of major reworks. I have recently tested the site in the Maxthon browser and confirmed functionality appears to be as expected.
