### ISSUE TITLE
[EDITOR] Common Chest

### ISSUE THREAD

**Issue by LilixMarias** [EliteMasterEric/Teyvat.moe#117]
The following data was generated by this user using the Editor mode. Any required images should be uploaded to this issue by dragging and dropping.
```
Common chest found in cave on Mt. Tianheng, Liyue. Chest is behind some smashable rocks
![common chest](https://user-images.githubusercontent.com/75723230/101604514-f16c2080-39f8-11eb-8877-1213fd4594e1.PNG)
![location](https://user-images.githubusercontent.com/75723230/101604782-4f006d00-39f9-11eb-81bb-dbf265e7aaa8.PNG)
```

**Comment by EliteMasterEric** [comment]
Hey, I appreciate the effort put into attempting to help with the mapping effort.

Since your image does not include the chest, this contribution will sadly be rejected. I hope that you will not be discouraged from making additional contributions in the future.
