### ISSUE TITLE
[QUESTION] On copy paste data

### ISSUE THREAD

**Issue by sgtoutlaw** [EliteMasterEric/Teyvat.moe#138]
I don't quite know how to ask questions using github interface, so this is the best I can do.

So, does it matter what # id I am starting with for the paste data, because it would be easier on me if I could keep my old editor data and just delete it from the paste as I submit it to better keep track of what I have already done.

**Comment by EliteMasterEric** [comment]
The IDs as you submit don't matter as I'll have to replace them anyway.
