### ISSUE TITLE
[BUG] Route deletion bug.

### ISSUE THREAD

**Issue by sgtoutlaw** [EliteMasterEric/Teyvat.moe#148]
**Describe the bug**
Cannot delete a route through the trash button.

**To Reproduce**
1. Go to the map
2. Enable the editor mode.
3. Use the routing function to make a route.
4. Navigate to the elements tab and try to use the Trash icon to delete the route.
5. There is no response, and the route is not deleted.

**Expected behavior**
I should be able to delete selected route, whereas right now I have to clear everything to get rid of it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox, chrome
 - Version 84.0 64 bit, 87.0.4280.88 64-bit)

**Comment by EliteMasterEric** [comment]
Okay, this one was funny. Apparently I had made a copy-paste mistake and hadn't replaced the word Marker with Route, so clicking the button would try and fail to delete a nonexistent marker instead of deleting the route.

Fix completed and tested, should be up on the Beta site soon.
