### ISSUE TITLE
[BUG] Performance issues when displaying chests

### ISSUE THREAD

**Issue by Jeinara** [EliteMasterEric/Teyvat.moe#154]
**Is your feature request related to a problem? Please describe.**
 When you turn on all of chests just for one region, map turns to be laggy. Very very laggy. My 
machine is not the weakest one, and browser is not the case, i tried different ones(Opera, Chrome, ect). And "two click to mark founded" feature in this situation just wont work because of lags.  
Cluster Markers helps, but then really hard to tell, wich chests already found, 'cause clusteres all looks same, opasity feature didnt work on them. 

**Describe the solution you'd like**
Some memory using impruvments or make some clear desing for clustered points. Like make cluster mark for all found marks transparent too.

**Comment by EliteMasterEric** [comment]
Thank you for testing the app. I've recategorized your request since performance issues are flaws in the software, not additional features to be added.

Can you provide some information about your computer's specifications? Even on my phone, performance is reasonably good.

**Comment by Jeinara** [comment]
Win 10, Ram 16gb, intel i5-3470 
Tried Opera Gx and Chrome
And Win 10. RAM 8gb. intel i7-8550u, Chrome
Both slow and laggy 
Do you need something else?
