### ISSUE TITLE
[BUG] Editor functions inaccessible.

### ISSUE THREAD

**Issue by sgtoutlaw** [EliteMasterEric/Teyvat.moe#155]
**Describe the bug**

**To Reproduce**
1. Open the map.
2. Turn on the editor mode.
3. The buttons used for editing overlap the zoom buttons, but lose their ability to be interacted with.

**Expected behavior**
The buttons should appear below the zoom buttons and I should be able to access the editor abilities by clicking them.

**Screenshots**

https://user-images.githubusercontent.com/35310360/102949794-2071a000-4497-11eb-933f-054360fdc55b.mp4

**Desktop (please complete the following information):

 - OS: Windows 10
 - Browser firefox, chrome
 - Version 84.0 64 bit, 87.0.4280.88 64-bit)

**Console error data if needed

Before hitting turning on editor mode.
![firefox_nveY1OI8xR](https://user-images.githubusercontent.com/35310360/102950233-3764c200-4498-11eb-8630-694bce8ea13c.png)

After turning on editor mode
![firefox_Szhgc7wEkt](https://user-images.githubusercontent.com/35310360/102950249-3f246680-4498-11eb-843d-30bc4296753d.png)

**Comment by EliteMasterEric** [comment]
v0.9.2, which should fix this, will be releasing as soon as Travis builds it.

In the meantime, check the Beta site and report bugs on that if you can.
