### ISSUE TITLE
[BUG] Region changing tabs are left behind when side menu is closed.

### ISSUE THREAD

**Issue by sgtoutlaw** [EliteMasterEric/Teyvat.moe#179]
**Describe the bug**
The region tabs from the section are left over after the menu has been closed, and are present in such a way even when the feature tab isn't in use.

**To Reproduce**

1. Go to The features tab of the side menu.
2. Take note of where the region tabs that stick out of the left of the menu are located.
3. Close the side menu.
4. Try and interact with the map where those region tabs were, and instead it tries to have to interact with the now invisible tabs.

**Screenshots**

https://user-images.githubusercontent.com/35310360/103143517-ba2e8c80-46e5-11eb-8892-0332d077ad0a.mp4

**Device Specs (please complete the following information):**

- GenshinMap app version: Beta version v0.9.4
- Device: PC
- OS: Windows 10
- Browser: Firefox
- Browser Version: 84.0.1 (64-bit)

**Additional context**
This had actually been causing me issues for a while, I just wasn't sure what the problem was.  
This is much more of a problem when I am resizing the window when using the map at the same time as playing the game, due to the much higher amount percentage of space this problem takes up when the window is smaller.

Edit:  I actually realized after, and edited the problem at the top slightly.  These side tabs are present at all times, no matter what tab or mode that is being used.  I thought for a second I could just change out of the features tab before I closed the menu but realized they are actually always there.

**Comment by EliteMasterEric** [comment]
Thanks for reporting.

The issue is that when the tabs hide, they currently only set their opacity. This means that they are still physically there and can block clicks.

I happened to notice this myself and I'm working on a fix.

**Comment by EliteMasterEric** [comment]
Fixed in v0.9.5.
