### ISSUE TITLE
[BUG] Bug report

### ISSUE THREAD

**Issue by Makishimu120** [EliteMasterEric/Teyvat.moe#183]
**Describe the bug**
Images are not loaded on new objects, for example from the path "https://genshinmap.github.io/comments/dragonspine/crimson-agate/crimson-agate-7.png"

**To Reproduce**

1. Go to 'new object (such as a chest)'
2. Click on 'object'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/74831656/103155292-6b4d2980-47af-11eb-9deb-ab65fa0f21c5.png)
![image](https://user-images.githubusercontent.com/74831656/103155368-5755f780-47b0-11eb-89f0-774742e573ec.png)

**Device Specs (please complete the following information):**

- GenshinMap app version: 0.9.4
- Device: PC
- OS: Windows 10
- Browser: chrome
- Browser Version: 87

**Error Message**

```

crimson-agate-7.png:1 GET https://genshinmap.github.io/comments/dragonspine/crimson-agate/crimson-agate-7.png 404


```
![image](https://user-images.githubusercontent.com/74831656/103155422-db0fe400-47b0-11eb-9259-80977ee51d17.png)

**Comment by EliteMasterEric** [comment]
This issue has now been fixed. The issue was the image had the JPG format, rather than PNG.

In the future, we should develop scripts to convert and optimize images as necessary (see #261).
