### ISSUE TITLE
[BUG] Bug report

### ISSUE THREAD

**Issue by Makishimu120** [EliteMasterEric/Teyvat.moe#184]
**Describe the bug**
There is a bug related to the main buttons. In Russian, they do not fit into the menu on the right.

**To Reproduce**

When the browser width changes, the right menu changes its width.

**Screenshots**
Width ~1920
![image](https://user-images.githubusercontent.com/74831656/103156216-80c65180-47b7-11eb-8b14-d7e197a0e88c.png)

Width ~900
![image](https://user-images.githubusercontent.com/74831656/103156587-1ca58c80-47bb-11eb-842b-8424a0efd962.png)

**Device Specs (please complete the following information):**

- GenshinMap app version: 0.9.4
- Device: PC
- OS: Windows 10
- Browser: chrome
- Browser Version: 87

**Additional context**
I played around with the font settings, and if you first add "fantasy" to the font-family (highlighted in yellow), then at any browser width, the text of the buttons fits and does not go beyond the frame.
![image](https://user-images.githubusercontent.com/74831656/103157363-1d422100-47c3-11eb-8772-163795284c7e.png)

![image](https://user-images.githubusercontent.com/74831656/103157353-07ccf700-47c3-11eb-9e4e-9aba215a61d9.png)

**Comment by EliteMasterEric** [comment]
The newest version uses icons and tooltips, making this no longer an issue.
