### ISSUE TITLE
[BUG] Mt. Aozang mispelled as "Mt. Aiozang"

### ISSUE THREAD

**Issue by grantwwu** [EliteMasterEric/Teyvat.moe#192]
**Describe the bug**

The mountain is mispelled.

**To Reproduce**

1. Go to map
2. Scroll to Mt. Aozang
3. See error.

**Screenshots**

![image](https://user-images.githubusercontent.com/4212965/103173497-64fb9380-4829-11eb-8074-46adc4b773e9.png)

**Device Specs (please complete the following information):**

- GenshinMap app version: 0.9.4
- Device: PC
- OS: Windows 10
- Browser: Chrome
- Browser Version: 87.0.4280.88

**Error Message**

**Additional context**

**Comment by EliteMasterEric** [comment]
Fixed in v0.9.5.
