### ISSUE TITLE
Site currently not loading.

### ISSUE THREAD

**Issue by klayd09** [EliteMasterEric/Teyvat.moe#21]
Why won't the map open?

**Comment by EliteMasterEric** [comment]
I recently merged a new beta version of the map. Please be patient as I figure out the Jenkins build system.

**Comment by EliteMasterEric** [comment]
![Capture](https://user-images.githubusercontent.com/4635334/97957864-0e6a5f80-1d7a-11eb-97d4-3ebdee7b14a6.PNG)

The new interface is now live for viewing.
