### ISSUE TITLE
[BUG] Single-click action fired when double-clicking

### ISSUE THREAD

**Issue by luanvilarim** [EliteMasterEric/Teyvat.moe#220]
When double-clicking a marker the pop-up opens and scrolls the map causing the marker to not be marked as completed.

**To Reproduce**

1. Go to Map
2. Double-Click on any marker with a video pop-up
3. See error

**Device Specs (please complete the following information):**

- GenshinMap app version: 0.9.4
- Device: PC
- OS: Windows 10
- Browser: Chrome, Brave, Opera 
- Browser Version: 87, 1.18.75, 73, respectively

**Comment by sgtoutlaw** [comment]
What he is talking about is in the instance that it is close enough to the side of the window that it will move the map to show the pop-up, you can't double click it.

Only way I could see this being 'fixed' is a slight delay on the appearance of the popup, or maybe just a delay in the popup making room to be seen.

**Comment by EliteMasterEric** [comment]
A slight delay in the appearance of the popup (about 300ms) is not too difficult and probably wouldn't cause too much inconvenience.

I was additionally looking into adding a switch to the popup the way Yuanshen.site does, but with how React and Leaflet interact that's a bit more difficult.

**Comment by EliteMasterEric** [comment]
Added in the v0.10.1 alpha version. 300ms is the timeout for single clicks currently. Windows uses 500ms but I felt that caused a noticeable delay in the popup appearing.
