### ISSUE TITLE
[EDITOR] Crystal

### ISSUE THREAD

**Issue by aantsu3** [EliteMasterEric/Teyvat.moe#278]
The following data was generated by this user using the Editor mode. Any required images should be uploaded to this issue by dragging and dropping.
```
THE EDITOR DATA SHOULD BE IN YOUR CLIPBOARD NOW. PASTE IT HERE.
```
![20f8658d-be4a-4928-aaf8-b5754f345fb2](https://user-images.githubusercontent.com/77245268/104132708-e3674200-53a0-11eb-823e-665be4df1762.jpg)

**Comment by EliteMasterEric** [comment]
Without the editor data, this doesn't help me.
