### ISSUE TITLE
[BUG] Bug report

### ISSUE THREAD

**Issue by rabidpug** [EliteMasterEric/Teyvat.moe#297]
When navigating to genshinmap.github.io nothing loads and the console logs `Error: Cannot find module './en.jsonc'`

DEFAULT_LOCALE_FILE in src/components/preferences/DefaultPreferences.js references `./${DEFAULT_LOCALE_CODE}.jsonc ` but the language files were changed to .json

**Comment by EliteMasterEric** [comment]
Working on a fix

**Comment by EliteMasterEric** [comment]
Once [this Travis build](https://travis-ci.org/github/GenshinMap/genshinmap.github.io/builds/757055210) finishes, the production page will be on the new version (v0.10.6) and should be available for use.
