### ISSUE TITLE
[CRASH] TypeError : t.coordinates is undefined

### ISSUE THREAD

**Issue by somnambula** [EliteMasterEric/Teyvat.moe#298]
**Describe the crash**

**Steps To Produce**

error on opening site
**Screenshots**

[screenshot](https://user-images.githubusercontent.com/29185482/106498706-50fe1e00-64c8-11eb-9e80-dfbdb37bb615.png)

**Device Specs (please complete the following information):**

- OS: Windows 10
- Browser: FIREFOX
- Browser Version: 85.0 (64)

**Additional context**

**Error Message**

```

TypeError : t.coordinates is undefined
Ai<@https://genshin-map-beta.netlify.app/static/js/main.ee67f565.chunk.js:1:2764693
w@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:247530
div
D/t</</f<@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:4809909
vo@https://genshin-map-beta.netlify.app/static/js/main.ee67f565.chunk.js:1:2732860
div
D/t</</f<@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:4809909
ru<@https://genshin-map-beta.netlify.app/static/js/main.ee67f565.chunk.js:1:2791098
w@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:247530
div
w@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:247530
f@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:245428
e@https://genshin-map-beta.netlify.app/static/js/main.ee67f565.chunk.js:1:2681790
t.a<@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:4805770
u/</C<@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:243612
t@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:431044
t.a@https://genshin-map-beta.netlify.app/static/js/2.199655d8.chunk.js:2:4804878

```

**Comment by batusawah** [comment]
i got same error 

OS: Windows 10
Browser: firefox
Browser Version: 82.0.2 (64-bit)

this error since yesterday

**Comment by EliteMasterEric** [comment]
Apologies, it seems that every time a major update for the game rolls around, the site coincidentally breaks and needs work.

@somnambula @batusawah v0.10.7 has been pushed to [the beta site](https://genshin-map-beta.netlify.app/). I don't think it will resolve your issue, but the change does revamp the error reporter to be more readable. Notice how the error message's stack trace currently contains random variables and references to chunk files? That's fixed, it references actual files I can reference now. Additionally, the site will attempt to export your current preferences (which includes completion data and options) so I can evaluate for errors.

Diagnosing and resolving your error will require you to visit the site again and submit a new error report.

**Comment by EliteMasterEric** [comment]
v0.10.7 was broken, and v0.10.8 has been pushed to fix it.

**Comment by EliteMasterEric** [comment]
@somnambula Please visit https://genshin-map-beta.netlify.app/ and verify that the app functions there. If it does not, please submit an error report as a new issue.
