### ISSUE TITLE
Map not working but for oculus

### ISSUE THREAD

**Issue by Fow-Fow** [EliteMasterEric/Teyvat.moe#30]
Hi,

The map is laoding, and dispalying stars for Oculus in anemo and geo tab. Other items (shrine, statue and teleporter) have no effect.
Monstres, Ore, Boss, plant... are empty.
![genshinmap github io](https://user-images.githubusercontent.com/73890583/97988989-28d62480-1dde-11eb-820f-a02455a3869e.png)

**Comment by Lou7xx** [comment]
yea, I experienced this too, also, can u export the previous file from this new version? I already marked so many chest back before but now I have to marked it all again huhu :(

**Comment by Draoken** [comment]
Yup, map is completely broken. RIP all my progress lol

**Comment by Jeinara** [comment]
Well, cookies still there, so there is hope too.
But yes, now map is broken

**Comment by Izuzusama** [comment]
I made a temporary backup website at https://izuzu.bitbucket.io/

To get all your old stuff back to the backup website

1. Goto https://genshinmap.github.io/
2. Press F12 on your keyboard
3. Select Console tab
4. Paste this into the console `prompt("Copy the below text: ", JSON.stringify(window.localStorage))`
5. Copy the content in the popup, you can now dismiss the popup
6. Goto https://izuzu.bitbucket.io/
7. Click on 'Import from genshinmap.github.io'
8. Paste the copied text and press OK

**Comment by EliteMasterEric** [comment]
See #34, I will be reverting the map to its previous version until the rework is complete.
