### ISSUE TITLE
[FEATURE] Feature request (One Domain description)

### ISSUE THREAD

**Issue by Alkmaaar** [EliteMasterEric/Teyvat.moe#314]
**Is your feature request related to a problem? Please describe.**
"Temple of the Lion" after some patch, you can pass tests of elemental reactions

**Describe the solution you'd like**
Add edit to description in English maybe it makes sense

**Comment by EliteMasterEric** [comment]
Just modified the description, changes should be reflected in v0.11.0 (currently in development).
