### ISSUE TITLE
Japanese language code is incorrect

### ISSUE THREAD

**Issue by Lapis256** [EliteMasterEric/Teyvat.moe#316]
The Japanese language file is jp.json, but it should be ja.json.

**Comment by EliteMasterEric** [comment]
Thank you for reporting this.

This issue would not cause problems with allowing the site to utilize the Japanese language, however it would prevent the browser from automatically detecting the native language of Japanese users and switching accordingly.

I'm trying to wrap up my next release soon, and I'll make a note to work on this bug after that.

**Comment by EliteMasterEric** [comment]
Resolved in v0.11.1.
