### ISSUE TITLE
[BUG] Broken menu in other languages

### ISSUE THREAD

**Issue by Jeinara** [EliteMasterEric/Teyvat.moe#330]
- GenshinMap app version: [0.11.2]
- Device: [PC]
- OS: [Windows 10]
- Browser: [Opera GX, Chrome]

![image](https://user-images.githubusercontent.com/12751573/111689024-8ffbef00-883c-11eb-830d-5c5d5aa47a61.png)
![image](https://user-images.githubusercontent.com/12751573/111689143-b6218f00-883c-11eb-9a14-cbee9c592f4a.png)
![image](https://user-images.githubusercontent.com/12751573/111689208-cc2f4f80-883c-11eb-91b8-400cd18beb44.png)
![image](https://user-images.githubusercontent.com/12751573/111689321-ef59ff00-883c-11eb-926f-f60493f9a83f.png)

**Comment by EliteMasterEric** [comment]
Other languages are known to be broken right now. I've got a fix in the works but it'll be a while.

**Comment by EliteMasterEric** [comment]
This is fixed in v0.12.
