### ISSUE TITLE
[BUG] Teleporter location on north Minlin island is in the wrong location.

### ISSUE THREAD

**Issue by alanmarkdm** [EliteMasterEric/Teyvat.moe#331]
**Describe the bug**

Teleporter in north Minlin is in the wrong location.  It is right on top of where the Stonehide Lawachurl spawns, rather than where it should be.

**To Reproduce**

Look a the north Minlin island.  Compare in game.

**Screenshots**

GenshinMap
![image](https://user-images.githubusercontent.com/24964081/111918664-8cdf4980-8a5c-11eb-9411-e6e0be7b499c.png)

In Game
![image](https://user-images.githubusercontent.com/24964081/111918729-f3646780-8a5c-11eb-9381-56c16ae1ffd6.png)

**Device Specs (please complete the following information):**

- GenshinMap app version: App version: v0.11.2
- Device: PC
- OS: Win10
- Browser: Chrome
- Browser Version: 89.0.4389.90 (Official Build) (64-bit)

**Error Message**

No Error

**Comment by EliteMasterEric** [comment]
Closed by #341.
