### ISSUE TITLE
[BUG] Teleporter location for Nantianmen is wrong.

### ISSUE THREAD

**Issue by alanmarkdm** [EliteMasterEric/Teyvat.moe#332]
**Describe the bug**

The teleporter in Nantianmen is not in the correct location.

**To Reproduce**

Look at the map.

**Screenshots**
GenshinMap:
![image](https://user-images.githubusercontent.com/24964081/111921904-7e4d5e00-8a6d-11eb-9b5c-1072770eee23.png)

In Game:
![image](https://user-images.githubusercontent.com/24964081/111921919-8907f300-8a6d-11eb-8a02-897640cff63a.png)

**Device Specs (please complete the following information):**

- GenshinMap app version: App version: v0.11.2
- Device: PC
- OS: Win10
- Browser: Chrome
- Browser Version: 89.0.4389.90 (Official Build) (64-bit)

**Error Message**

No Error

**Comment by EliteMasterEric** [comment]
Closed by #341.
