### ISSUE TITLE
[ANNOUNCEMENT] Page Reversion

### ISSUE THREAD

**Issue by EliteMasterEric** [EliteMasterEric/Teyvat.moe#34]
For those users wondering about this site:

I have been developing a major rework, to make it easier to develop and to contribute to the site.

Sadly, some users are not happy as this rework is not currently at feature parity with the existing site, and several are complaining that their data is completely gone.

**I made a mistake here. I will be reverting the site pending the completion of the rework to people's expectations.** 

Data has not been wiped, it is simply not visible. My immediate first priority is to add a new feature which will export the data from the old version of the site such that users can migrate to a fork of the old site (available at https://izuzu.bitbucket.io/).

At a future point, once this site reaches parity with the old site, there will be an importer which accepts this old data format.

**Comment by Izuzusama** [comment]
I would suggest just to keep the gh-pages branch as the old version while you work on the reworked version

**Comment by EliteMasterEric** [comment]
That works, I'm going to do that now.

The displayed branch will now be `gh-pages-legacy`, which is the old version of the map.

**Comment by EliteMasterEric** [comment]
With version 0.8.1, the reworked version is now in a stable and feature-complete state. It is now a vast improvement over the original site.

If you have any issues using the site, please create a new issue on this repo.
