### ISSUE TITLE
[BUG] Can't use migrate from github.io button

### ISSUE THREAD

**Issue by Jeinara** [EliteMasterEric/Teyvat.moe#377]
![image](https://user-images.githubusercontent.com/12751573/121818080-bd1a3b00-cc8d-11eb-9407-df2b7fa7c57e.png)
![image](https://user-images.githubusercontent.com/12751573/121818116-f0f56080-cc8d-11eb-86a1-77be43f3137e.png)
![image](https://user-images.githubusercontent.com/12751573/121818143-15e9d380-cc8e-11eb-94f6-855341dba230.png)

**Comment by EliteMasterEric** [comment]
Thanks for reporting, I am looking into this issue.

**Comment by EliteMasterEric** [comment]
@Jeinara Can you please check out https://develop.teyvat.moe/map, check if the app version is v1.1.1, and determine if these errors appear for you there?

**Comment by Jeinara** [comment]
App version is v1.1.1
![image](https://user-images.githubusercontent.com/12751573/121899240-e3db7e80-cd2c-11eb-8f1c-1df84775bd0b.png)
Now it looks like this. Looks like there is no resp. infinite load bar.

**Comment by EliteMasterEric** [comment]
@Jeinara Thank you for reporting. It appears you encountered a second, separate bug with the migrator where it only functioned on the main site.

This issue has now been fixed, and I have confirmed it is working myself at least on the develop site. Let me know if the issue happens again and I can reopen if needed.
