### ISSUE TITLE
[MAPPING] Geo Sigil Rocks and Crates

### ISSUE THREAD

**Issue by birth23** [EliteMasterEric/Teyvat.moe#42]
Can we start a Geo Sigil Category where we can locate the Geo sigil rocks and the crates in the water?  I attached some pictures of what I am talking about. 

![5](https://user-images.githubusercontent.com/73905331/98283141-30780380-1f6d-11eb-8633-2952ef30d7c4.png)
![4](https://user-images.githubusercontent.com/73905331/98282490-4d600700-1f6c-11eb-8952-3c83f47962a1.png)
![3](https://user-images.githubusercontent.com/73905331/98282499-505af780-1f6c-11eb-88b3-a9585bef0cd9.png)

**Comment by EliteMasterEric** [comment]
New Geo Sigil and Crate features have been added to the Chests category.

If any community members would like to aid in the task of mapping these, it would be greatly appreciated.
