### ISSUE TITLE
Beta website is not functional. Returning Page Not Found Error

### ISSUE THREAD

**Issue by birth23** [EliteMasterEric/Teyvat.moe#43]
The Beta website that is currently mapped to:  https://genshin-map-beta.netlify.app/  is returning Page Not Found
![image](https://user-images.githubusercontent.com/73905331/98283629-ecd1c980-1f6d-11eb-8fda-3f04a514ba93.png)

**Comment by EliteMasterEric** [comment]
This is due to a failed build on Netlify. The build failed because ESLint detected several code style issues, and Netlify interprets warnings as errors. These should be resolved shortly.
