### ISSUE TITLE
[FEATURE] Add User Progress Summary Tab

### ISSUE THREAD

**Issue by birth23** [EliteMasterEric/Teyvat.moe#48]
Add a User Summary progress tab:
Mondstadat Anemocolus found/Total
Mondstadt chest opened/total chests
Recourses summary: Picked up/Total (resets after time?)

Liyue Geocolus/Total
Liyue chest opened/total chests
Recourses Summary:  Picked up/total (resets after time?)

TimeStamp when recourses are picked up, to keep track of respawn times.  When recourses are picked up a timestamp will be shown in a popup when item is selected  #5 
Add a button in the summary tab that will trigger a script that checks the time stamp on the resources markers and revert to the unpicked status if the estimated respawn time has been exceeded.  
So for example if crystal is changed to Done, and the button in summary tab is pressed after 72 hours, the crystall will be reverted to the not done status

**Comment by EliteMasterEric** [comment]
Here's how I would do this issue:

Add a Summary tab which provides the number of markers on each feature you have marked as done, compared to the total number available on the map. The summary is available for all features (not just Oculi), but a feature only appears in the Summary tab if at least one marker has been set as completed.

Add information on respawn duration to the data files. In the Summary Tab, next to the completion rates, there are buttons to Clear All Marks, or Clear Respawned Marks (which compares with the timestamp that you flagged the mark as completed with the current time and the specified respawn duration, and only clears completed status on the markers that should have respawned). To prevent confusion on the user's part this process should be manual; they click the button to trigger the respawn check.

**Comment by EliteMasterEric** [comment]
Added in v0.4.0.
