### ISSUE TITLE
[CHEST] I have the picture of the no.1136 chest

### ISSUE THREAD

**Issue by WenshiTakahashi** [EliteMasterEric/Teyvat.moe#51]
**Describe each chest modification you wish to make.**
No.1136, Common Chest, behind the breakable rocks.
(I'm entirely noob to these things but I wanna contribute something back.)

**Additional context**
![image](https://user-images.githubusercontent.com/74184751/98534832-a6ef6b00-22b7-11eb-96dc-620e6454b5db.png)

**Comment by EliteMasterEric** [comment]
Sorry for the delay, thank you for the contribution!

The newest version of the map will include your location correction and image.
