### ISSUE TITLE
[FEATURE] New Website Domain Name

### ISSUE THREAD

**Issue by EliteMasterEric** [EliteMasterEric/Teyvat.moe#87]
If there is enough interest and community support for this project, I may consider purchasing a new domain which would redirect to the map. The site would still be hosted on GitHub, it would simply act as an alias.

If the decision to do this is made, which domain should be used?

* The domain should ideally be VERY short and easy to remember, like one word and a TLD.
* Some keywords to be used for the domain could be `Genshin`, GenshinMap`, Teyvat`,
* `.com` is a very easy TLD to remember but for some domains it can be expensive or already taken.
* Widely used TLDs like `.org` and `.net` are available and cheap, but also boring.
* `.map` domains are not available for sale as far as I can tell. `.ap` ending does not exist.
* `.io` is cool, hip, and easy to remember, but costs several times more than other domains.
* Some fun TLDs like `.moe` are available.

**Comment by schrmh** [comment]
Maybe ask https://www.gensh.in/ wether they would redirect map.gensh.in or gensh.in/map

**Comment by EliteMasterEric** [comment]
Move to #246.
