### ISSUE TITLE
Progress lost

### ISSUE THREAD

**Issue by mamadoh2** [EliteMasterEric/Teyvat.moe#93]
all my progress has been lost after this new beta update
is there a way to get my progress back?

**Comment by Urtemiel** [comment]
> Hello! Thank you for taking the time to submit feedback to the GenshinMap project. Your issue will be reviewed shortly.

similar problem

**Comment by vitalii-ivanov-gl** [comment]
similar, and also there is no possibility to pick something from liyue on the map

**Comment by paulo27ms** [comment]
> similar, and also there is no possibility to pick something from liyue on the map

You need to lower you browser zoom to show the area tabs.

**Comment by mamadoh2** [comment]
> > similar, and also there is no possibility to pick something from liyue on the map
> 
> You need to lower you browser zoom to show the area tabs.

thanx I didn't know this, I thought it was  WIP

**Comment by EliteMasterEric** [comment]
Hello,

It appears you are having issues importing your data from a legacy version of the site. Thankfully, this is an easy process, and [there is a guide on the wiki](https://github.com/GenshinMap/genshinmap.github.io/wiki/Frequently-Asked-Questions#how-do-i-transfer-my-data-from-the-old-version-of-genshinmap) on how to do it.

As for the issue of not being able to see markers in other regions, this is a known bug that I'm working on solving now.

**Comment by mamadoh2** [comment]
> Hello,
> 
> It appears you are having issues importing your data from a legacy version of the site. Thankfully, this is an easy process, and [there is a guide on the wiki](https://github.com/GenshinMap/genshinmap.github.io/wiki/Frequently-Asked-Questions#how-do-i-transfer-my-data-from-the-old-version-of-genshinmap) on how to do it.
> 
> As for the issue of not being able to see markers in other regions, this is a known bug that I'm working on solving now.

**Comment by mamadoh2** [comment]
thank you and sorry for not checking the FAQ

**Comment by mamadoh2** [comment]
> > Hello,
> > It appears you are having issues importing your data from a legacy version of the site. Thankfully, this is an easy process, and [there is a guide on the wiki](https://github.com/GenshinMap/genshinmap.github.io/wiki/Frequently-Asked-Questions#how-do-i-transfer-my-data-from-the-old-version-of-genshinmap) on how to do it.
> > As for the issue of not being able to see markers in other regions, this is a known bug that I'm working on solving now.

thank you and sorry for not checking the FAQ

**Comment by Urtemiel** [comment]
> Hello,
> 
> It appears you are having issues importing your data from a legacy version of the site. Thankfully, this is an easy process, and [there is a guide on the wiki](https://github.com/GenshinMap/genshinmap.github.io/wiki/Frequently-Asked-Questions#how-do-i-transfer-my-data-from-the-old-version-of-genshinmap) on how to do it.
> 
dont work

**Comment by EliteMasterEric** [comment]
> dont work

This doesn't help me. What are the symptoms you are experiencing? Please be more specific.

I'm working on an update which will improve the importer and add error messages to the dialog box. In the meantime if you're on Chrome or Firefox you can press F12 to open the console, which will print out any errors you are experiencing (again, update coming soon to make this more accessible).

**Comment by Urtemiel** [comment]
Opera gx browser
When importing data, all labels remain empty

Data:
["26_408","27_934","27_806","27_161","26_83","27_565","26_47","26_22","26_277","27_434","27_914","27_831","27_603","27_757","26_213","26_7","27_690","27_150","27_928","27_1140","27_752","26_381","26_218","26_350","26_134","27_69","27_115","27_226","27_108","27_1077","26_255","26_331","27_122","27_116","26_200","6_1","27_929","27_157","26_317","26_487","27_230","27_5","26_104","27_921","26_11","26_386","26_407","27_426","27_158","27_193","27_199","26_413","27_1041","26_43","26_20","27_790","27_101","27_538","26_12","26_290","26_57","27_468","26_348","27_32","27_791","26_189","26_297","27_196","27_546","27_606","27_135","27_1146","27_96","27_945","27_130","26_167","26_156","26_131","26_286","27_671","27_918","26_258","26_227","26_306","27_592","26_292","27_147","27_846","26_324","26_379","27_177","27_1081","27_537","26_363","26_446","27_257","27_802","27_788","26_299","26_389","26_46","26_307","26_223","27_930","26_474","27_506","26_392","26_214","27_499","26_252","27_542","27_1061","26_338","26_451","26_449","26_222","26_158","26_21","27_571","26_42","27_804","26_502","27_262","27_493","26_41","26_415","27_562","26_491","26_410","27_897","27_937","27_44","27_232","27_675","27_166","26_9","27_689","26_23","27_246","27_435","27_764","6_2","26_121","26_51","27_533","27_355","26_342","26_152","26_62","27_176","27_595","27_783","27_1141","26_517","26_94","27_1084","27_215","26_380","26_438","27_1068","26_117","26_325","26_512","27_553","27_129","26_99","26_194","26_50","26_450","27_61","27_76","27_793","26_40","26_341","27_605","27_118","27_920","26_456","27_566","27_194","26_199","27_576","27_830","26_346","26_434","26_393","27_640","27_564","27_94","27_855","26_273","27_454","27_291","26_377","27_75","26_59","26_90","26_76","26_291","27_680","27_217","26_190","26_503","27_80","26_366","27_696","26_32","26_38","27_627","27_560","26_89","27_144","27_803","27_594","26_443","27_875","27_469","26_13","26_164","27_763","27_424","27_568","27_263","27_114","27_532","26_107","26_1","27_141","27_814","26_473","27_428","27_433","27_357","26_430","26_118","27_1113","27_668","27_1147","26_275","27_1030","26_241","27_214","27_460","26_361","27_185","27_683","26_494","27_486","27_976","26_470","27_607","26_391","26_368","27_912","26_8","27_1064","27_453","27_79","27_833","27_684","26_220","26_262","27_795","27_137","27_692","26_294","27_540","26_312","27_109","27_873","26_323","26_416","27_539","27_30","26_31","27_1076","26_526","26_316","27_227","26_35","27_98","26_231","26_442","27_745","27_794","26_92","26_293","26_29","26_251","26_55","27_681","26_484","26_455","26_10","26_482","27_904","26_111","26_245","27_236","26_219","27_152","26_483","26_472","26_440","27_657","27_847","27_694","26_119","26_150","27_187","27_123","26_2","26_528","26_34","27_850","26_420","26_240","26_58","27_77","27_769","26_135","26_185","27_1150","26_287","26_453","27_1065","26_168","26_211","27_557","26_183","26_69","27_817","26_204","26_354","27_782","27_151","26_250","27_386","26_439","27_853","27_736","27_574","26_215","26_427","26_496","27_117","26_459","26_475","26_84","27_760","27_741","26_437","27_216","27_162","26_70","27_647","26_235","27_672","26_318","26_524","27_1087","27_509","26_351","27_1058","26_423","26_288","26_226","27_149","27_971","26_257","26_5","27_138","27_753","27_175","27_857","27_593","27_112","26_327","26_501","26_106","27_133","27_955","27_173","26_527","26_375","27_554","27_1138","27_938","27_673","27_522","26_498","27_272","27_97","27_541","26_352","27_762","27_457","27_737","27_569","26_355","27_743","27_580","27_326","26_272","26_418","26_328","26_26","26_412","27_639","27_266","26_448","27_812","26_210","27_70","26_248","27_126","27_911","26_202","26_436","27_523","27_1094","27_1135","26_426","27_458","26_304","26_398","26_457","26_402","27_954","27_195","26_45","26_343","26_28","27_192","27_787","26_492","26_478","27_373","26_216","26_242","27_845","26_489","26_68","26_335","26_347","27_93","27_174","26_339","27_459","27_31","26_254","27_872","27_482","27_800","26_161","26_283","26_25","26_396","27_179","26_333","26_260","26_188","27_1033","26_535","27_1028","27_682","26_414","26_171","27_1001","27_784","26_428","26_53","26_269","27_136","26_534","27_189","26_177","27_72","27_2","27_184","27_1080","27_466","26_360","26_6","27_190","26_61","27_1118","27_261","27_851","26_383","27_1115","26_123","26_228","27_899","27_120","26_425","27_170","26_160","27_674","27_664","26_197","26_37","26_507","27_84","27_547","26_74","27_1078","26_421","26_132","27_376","26_225","26_79","27_1083","27_496","27_754","27_461","27_771","27_473","27_180","27_691","27_980","27_658","26_124","26_208","27_483","27_82","27_590","26_212","26_506","26_157","26_285","27_198","27_676","27_160","26_91","26_447","27_500","27_876","27_748","27_491","27_74","27_1063","26_424","27_734","26_229","26_522","27_648","27_940","27_896","27_686","26_280","27_186","27_1075","26_270","27_1079","26_388","27_494","26_356","26_249","27_746","27_548","26_276","26_221","26_401","26_56","27_1109","26_429","27_165","27_1","26_81","26_373","26_458","27_1111","26_340","27_598","27_629","27_1057","27_563","26_419","26_481","27_596","26_120","27_1110","27_484","27_816","26_334","27_125","27_599","27_585","26_525","27_105","27_765","26_108","26_102","27_601","27_156","26_471","26_433","27_260","26_495","26_298","26_162","26_52","26_155","26_476","27_511","27_772","27_252","26_301","26_236","26_233","26_387","27_567","27_1040","26_256","26_315","27_3","27_1082","27_635","26_488","27_999","27_251","27_738","27_578","26_179","26_17","27_813","27_439","27_231","26_378","26_127","26_370","26_358","27_895","26_384","27_1062","27_900","27_146","26_88","26_77","27_253","27_545","27_103","26_309","27_1069","26_36","26_508","27_677","26_467","27_487","26_72","26_192","27_559","27_490","27_7","26_295","27_172","26_296","26_15","26_265","27_555","26_422","26_371","26_395","26_33","27_1120","27_164","26_394","27_100","26_73","27_39","26_497","26_67","27_932","27_575","26_266","27_23","26_510","27_159","27_153","27_693","27_265","27_667","27_248","27_4","26_181","26_303","27_701","26_30","26_537","27_552","26_239","27_95","26_163","26_246","26_178","27_549","27_998","27_597","26_133","27_167","27_926","27_848","27_155","27_425","27_679","26_105","26_406","26_64","26_302","27_981","26_499","27_168","27_1133","27_9","27_797","26_259","27_259","26_82","27_85","26_314","26_54","26_337","26_129","26_39","26_98","26_176","27_699","26_310","27_687","27_818","26_385","26_182","26_382","26_264","27_556","27_124","27_756","27_508","27_697","27_99","26_159","27_1034","27_550","27_528","26_93","27_233","27_589","27_33","26_319","27_534","26_466","27_551","26_374","26_230","26_330","26_263","26_313","26_100","27_140","27_492","27_102","27_1142","26_151","27_811","27_570","26_523","27_755","27_145","27_455","27_702","26_417","26_477","26_4","26_500","26_78","27_588","27_501","27_1066","26_85","27_6","26_349","26_87","26_206","27_377","27_8","27_495","26_365","27_264","27_183","27_1139","27_1116","27_249","26_320","27_143","27_106","27_197","26_193","27_700","26_336","26_195","27_780","27_573","26_490","27_805","27_111","27_688","27_467","26_253","27_1114","27_271","26_432","27_374","27_798","27_792","26_65","27_378","26_247","27_127","27_878","27_163","26_513","27_865","27_1029","26_44","27_735","27_758","26_515","27_952","27_1134","27_698","26_278","26_271","27_670","27_67","27_561","26_493","26_399","27_939","26_397","26_80","27_1032","27_200","27_131","27_1059","26_49","26_60","26_166","27_472","26_345","27_132","27_107","26_97","27_894","26_329","6_35","27_785","26_16","27_905","27_78","27_498","27_744","26_444","26_187","27_801","27_666","26_3","27_427","27_363","27_685","26_445","27_913","26_201","27_935","27_485","27_669","27_121","26_128","27_977","26_369","27_169","26_504","26_186","27_387","27_527","27_429","26_322","27_636","26_71","26_243","26_409","26_353","26_359","26_435","27_936","26_19","27_665","27_225","27_73","26_267","27_178","26_405","27_974","26_362","27_815","26_234","26_311","26_66","26_205","26_63","27_471","27_81","27_1067","27_362","27_931","26_24","26_261","26_332","27_148","26_532","27_456","27_218","27_1026","26_122","27_825","27_927","26_281","27_925","27_255","27_182","26_364","26_224","26_207","26_479","27_854","27_191","27_497","26_441","26_27","26_308","27_256","27_247","27_134","27_270","27_768","26_209","26_48","26_180","27_558","27_941","27_462","26_344","26_203","27_915","27_254","26_431","27_1085","27_544","27_119","27_796","27_628","27_510","26_75","26_244","27_572","27_901","27_695","26_96","27_181","27_577","27_874","26_300","27_128","26_217","27_139","26_514","27_579","26_232","27_747","27_703","26_390","26_237","26_14","27_526","27_470","26_170","26_282","26_411"]

**Comment by Urtemiel** [comment]
ty for fix<3

**Comment by EliteMasterEric** [comment]
This issue has hopefully been resolved in v0.8.3. Any other issues with the importer should go to #94 or a new issue.
