### ISSUE TITLE
[BUG] Can't show markers for Liyue

### ISSUE THREAD

**Issue by Failsomebody** [EliteMasterEric/Teyvat.moe#95]
I can't find any way of showing markers for Liyue. Everything is set to Mondstadt.

**Comment by paulo27ms** [comment]
See https://github.com/GenshinMap/genshinmap.github.io/issues/93#issuecomment-738130008

**Comment by EliteMasterEric** [comment]
Hey,

I can confirm this is a bug. There's supposed to be a set of tabs on the left side of the map controls, when you're on the Features or Routes tab.

I just pushed a fix, can you see them now? If you can't, the page may be cached, and you may need to [refresh your cache](https://refreshyourcache.com/en/cache/).

(Also, it only just occurred to me that those tabs would not be visible in the mobile view. I'll have to fix that).

**Comment by Failsomebody** [comment]
I refreshed my cache and it didn't show up. But for some reason I can see it when I use a private window on Firefox. 
Edit: Can see it with 80% zoom.

**Comment by EliteMasterEric** [comment]
Hey,

I figured out the source of the issue. The menu changes size at certain resolutions, and at higher resolutions the menu becomes too large and the region tabs are behind it.

**Comment by EliteMasterEric** [comment]
Version 0.8.2 should fix this issue.

**Comment by Failsomebody** [comment]
Yes it is visible now.
