### ISSUE TITLE
[EDITOR] Chest

### ISSUE THREAD

**Issue by ShalltearFR** [EliteMasterEric/Teyvat.moe#98]
There is a chest here.
![Sans titre](https://user-images.githubusercontent.com/20574430/101193088-54a62d80-365c-11eb-9c46-fcdcab10e101.jpg)
![Sans titre](https://user-images.githubusercontent.com/20574430/101193148-6ee00b80-365c-11eb-8f3d-64edf2d2c1bf.jpg)

**Comment by EliteMasterEric** [comment]
What type of chest? Common, Exquisite, Precious?

**Comment by EliteMasterEric** [comment]
No followup, closing for bad data.
