### ISSUE TITLE
[EDITOR] Chest

### ISSUE THREAD

**Issue by ShalltearFR** [EliteMasterEric/Teyvat.moe#99]
There is a chest here
![Sans titre](https://user-images.githubusercontent.com/20574430/101194689-9c2db900-365e-11eb-98b5-3406b5479d52.jpg)
![image](https://user-images.githubusercontent.com/20574430/101194730-a8b21180-365e-11eb-8c0c-bda49f4f7f8e.png)

**Comment by EliteMasterEric** [comment]
What type of chest? Common, Exquisite, or Precious?

**Comment by EliteMasterEric** [comment]
No followup, closing due to bad data.
